import 'dart:io';
import 'package:path/path.dart' as path;
import '../schema/env_schema.dart';
import '../schema/schema_loader.dart';
import '../encryption/encryption_service.dart';

/// Generates the EnvConfig class from a schema.
class EnvConfigGenerator {
  final EnvSchema schema;
  final String? masterKey;

  EnvConfigGenerator({
    required this.schema,
    this.masterKey,
  });

  /// Generates the Dart code for EnvConfig class.
  String generate() {
    final buffer = StringBuffer();
    
    // Header
    buffer.writeln('// GENERATED CODE - DO NOT MODIFY');
    buffer.writeln('// This file was generated by secure_env_manager');
    buffer.writeln('');
    buffer.writeln("import 'package:secure_env_manager/secure_env_manager.dart';");
    buffer.writeln("import 'dart:io';");
    buffer.writeln('');

    // Class definition
    buffer.writeln('/// Generated environment configuration class.');
    buffer.writeln('class EnvConfig {');
    buffer.writeln('  EnvConfig._();');
    buffer.writeln('');

    // Static instance
    buffer.writeln('  static EnvConfig? _instance;');
    buffer.writeln('  static EnvConfig get instance {');
    buffer.writeln('    _instance ??= EnvConfig._();');
    buffer.writeln('    return _instance!;');
    buffer.writeln('  }');
    buffer.writeln('');

    // Master key
    if (masterKey != null) {
      buffer.writeln("  static const String _masterKey = '$masterKey';");
      buffer.writeln('');
    } else {
      buffer.writeln('  static String? _masterKey;');
      buffer.writeln('');
      buffer.writeln('  /// Sets the master key for decryption.');
      buffer.writeln('  static void setMasterKey(String key) {');
      buffer.writeln('    _masterKey = key;');
      buffer.writeln('  }');
      buffer.writeln('');
    }

    // Environment values cache
    buffer.writeln('  static Map<String, String>? _envValues;');
    buffer.writeln('');
    buffer.writeln('  static Map<String, String> _loadEnvValues() {');
    buffer.writeln('    if (_envValues != null) return _envValues!;');
    buffer.writeln('    _envValues = Platform.environment;');
    buffer.writeln('    return _envValues!;');
    buffer.writeln('  }');
    buffer.writeln('');

    // Generate getters for each field
    for (final field in schema.fields) {
      _generateFieldGetter(buffer, field);
    }

    // Helper methods
    _generateHelperMethods(buffer);

    buffer.writeln('}');
    return buffer.toString();
  }

  void _generateFieldGetter(StringBuffer buffer, field) {
    final fieldName = _toCamelCase(field.name);
    final type = field.type;
    final defaultValue = field.defaultValue;
    final required = field.required;
    final encrypted = field.encrypted;

    buffer.writeln('  /// ${field.description ?? field.name}');
    buffer.writeln('  $type get $fieldName {');
    buffer.writeln("    final value = _loadEnvValues()['${field.name}'];");
    
    if (required && defaultValue == null) {
      buffer.writeln("    if (value == null) {");
      buffer.writeln("      throw StateError('Required environment variable ${field.name} is not set');");
      buffer.writeln('    }');
    } else if (defaultValue != null) {
      buffer.writeln("    if (value == null) {");
      if (type == 'String') {
        buffer.writeln("      return '${defaultValue.toString().replaceAll("'", "\\'")}';");
      } else {
        buffer.writeln('      return $defaultValue;');
      }
      buffer.writeln('    }');
    } else {
      buffer.writeln('    if (value == null) return null;');
    }

    if (encrypted) {
      buffer.writeln('    if (_masterKey == null) {');
      buffer.writeln("      throw StateError('Master key not set. Call EnvConfig.setMasterKey() first.');");
      buffer.writeln('    }');
      buffer.writeln('    final decrypted = EncryptionService.decrypt(value, _masterKey!);');
      buffer.writeln('    return _parse$type(decrypted);');
    } else {
      buffer.writeln('    return _parse$type(value!);');
    }

    buffer.writeln('  }');
    buffer.writeln('');
  }

  void _generateHelperMethods(StringBuffer buffer) {
    buffer.writeln('  // Helper methods for type parsing');
    buffer.writeln('  String _parseString(String value) => value;');
    buffer.writeln('  int _parseint(String value) => int.parse(value);');
    buffer.writeln('  bool _parsebool(String value) => value.toLowerCase() == \'true\';');
    buffer.writeln('  double _parsedouble(String value) => double.parse(value);');
    buffer.writeln('');
  }

  String _toCamelCase(String input) {
    final parts = input.split(RegExp(r'[_\s-]+'));
    if (parts.isEmpty) return input.toLowerCase();
    
    final first = parts[0].toLowerCase();
    final rest = parts.skip(1).map((p) {
      if (p.isEmpty) return '';
      return p[0].toUpperCase() + p.substring(1).toLowerCase();
    }).join('');
    
    return first + rest;
  }
}

